### ISSUE TITLE
Cannot visualize topography maps

### ISSUE THREAD

**Issue by ovizii** [ninech/netbox-docker#100]
access netbox, go to admin, topology maps, create new map with device pattern: * 

I then try accessing the map and get: 

> There was an error generating the requested graph. Ensure that the GraphViz executables have been installed correctly.

The url looks like: http://internal-docker:8777/api/extras/topology-maps/1/render/

## Expected Behavior

See a topology map
...

## Debug Information

The output of `docker-compose version`: 

docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

The output of `docker version`: 

Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

The output of `git rev-parse HEAD`: `81f8c7386d430358aa0f140f3d3e6a188cf9a47e`
The command you used to start the project: `As detailed here: https://github.com/ninech/netbox-docker#quickstart`

The output of `docker-compose logs netbox`:
https://gist.github.com/ovizii/575c37b4a815bf5997592682bbfeee52

**Comment by cimnine** [comment]
This is weird, as Graphviz is clearly installed:

https://github.com/ninech/netbox-docker/blob/81f8c7386d430358aa0f140f3d3e6a188cf9a47e/Dockerfile#L8

**Comment by ovizii** [comment]
It might be me messing things up, I'm quite new to Docker. Maybe this could be the cause? I wanted to map data into specific folders for backup purposes instead of using the docker volumes: 

docker-compose.yml

```
version: '3'
services:
  netbox: &netbox
    build:
      context: .
      args:
        - BRANCH=${VERSION-master}
    image: ninech/netbox:${VERSION-latest}
    depends_on:
    - postgres
    - redis
    - netbox-worker
    env_file: env/netbox.env
    volumes:
    - ./startup_scripts:/opt/netbox/startup_scripts:ro
    - ./initializers:/opt/netbox/initializers:ro
    - ./configuration:/etc/netbox/config:ro
    - /mnt/netbox/netbox-nginx-config:/etc/netbox-nginx/
    - /mnt/netbox/netbox-static-files:/opt/netbox/netbox/static
    - /mnt/netbox/netbox-media-files:/opt/netbox/netbox/media
    - /mnt/netbox/netbox-report-files:/etc/netbox/reports:ro
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.15-alpine
    depends_on:
    - netbox
    ports:
    - 8777:8080
    volumes:
    - /mnt/netbox/netbox-static-files:/opt/netbox/netbox/static:ro
    - /mnt/netbox/netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:10.4-alpine
    env_file: env/postgres.env
    volumes:
    - /mnt/netbox/netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:4-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
    - /mnt/netbox/netbox-redis-data:/data
```
Look at the volumes section. This had led to me having to manually copy the nginx.conf file into: /mnt/netbox/netbox-nginx-config 

Maybe that is unnecessary? Would it be enough to map the postgres data into a folder for backup and reverse the other changes I made to volumes? 
```
  postgres:
    image: postgres:10.4-alpine
    env_file: env/postgres.env
    volumes:
    - /mnt/netbox/netbox-postgres-data:/var/lib/postgresql/data

```
