### ISSUE TITLE
Static port

### ISSUE THREAD

**Issue by hexicans** [ninech/netbox-docker#113]
Hello,
after restart docker, netbox change port.. how to get static port with docker compose ? 

Thanks

**Comment by cimnine** [comment]
Change the ports in the `docker-compose.yml` file. Consult the [docker-compose manual][dc-man] for this.

Something like this:

```yaml
services:
  nginx:
    ports:
    - 8080:8080
```

[dc-man]: https://docs.docker.com/compose/compose-file/#short-syntax-1
