### ISSUE TITLE
How do you upgrade 2.1.6 -2.2.2

### ISSUE THREAD

**Issue by RyanD0001** [ninech/netbox-docker#19]
Hi,

I need to upgrade 2.1.6 to 2.2.2 I can't rebuild because I can't restore my db afterwards.

Thanks,

Ryan

**Comment by cimnine** [comment]
Can you please create a [gist](gist.github.com) with your current `docker-compose.yml` and add the link here?

**Comment by RyanD0001** [comment]
here you go

https://gist.github.com/RyanD0001/e4cd0a884b0cae94f480ed52e0e2a4c0

**Comment by cimnine** [comment]
What happens if you gradually update the version of the container? It should actually upgrade the database automagically.

**Comment by RyanD0001** [comment]
How do I this?

**Comment by cimnine** [comment]
```
version: '3'
services:
    netbox:
        build:
          context: .
          #args:
           # - BRANCH=${VERSION-master}
        image: ninech/netbox:v2.1.6
        depends_on:
        - postgres
        env_file: netbox.env
        volumes:
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
    nginx:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - 80
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-nginx-config:/etc/netbox-nginx/
    postgres:
        image: postgres:9.6-alpine
        env_file: postgres.env

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
```

Run `dc up -d`, then `dc stop netbox`. Now change the version, at least 2.2.1:

```
version: '3'
services:
    netbox:
        build:
          context: .
          #args:
           # - BRANCH=${VERSION-master}
        image: ninech/netbox:v2.2.2
        depends_on:
        - postgres
        env_file: netbox.env
        volumes:
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
    nginx:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - 80
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-nginx-config:/etc/netbox-nginx/
    postgres:
        image: postgres:9.6-alpine
        env_file: postgres.env

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
```

Then again `dc up netbox`. It should start migrating the db.
