### ISSUE TITLE
Define custom fields in YAML

### ISSUE THREAD

**Issue by cimnine** [ninech/netbox-docker#40]
## Current Behavior

When #39 is merged, we have a very rudimentary way to perform certain actions when launching the container.

## Expected Behavior

It would be cool though if, instead of writing python code to import custom fields, a more general script existed which would would parse a yaml; a file I imagine to look like this:

```yml
custom_field_name:
  on_objects:
  - dcim.models.Device
  - dcim.models.DeviceType
  type: CF_TYPE_TEXT
  label: The Label
  description: The Description
  required: true
  filterable: true
  default: nil
  weight: 100
  choices:
  - value: Choice 1
    weight: 100
```
