### ISSUE TITLE
Render custom_fields.yml with jinja

### ISSUE THREAD

**Issue by Grokzen** [ninech/netbox-docker#74]
Hi.

This is more of a question/poll if this feature would be accepted if i would put down the time to develop a rendering functionality of this file.

Basically the use-case that i found is where i need to make a bunch of items that needs a increased number in the value in a selection field for example. For example a field where i need something like this

```
....
- value: foo1
- value: foo2
- value: foo3
....
- value: foo100
```

And if i need something like 100-200 of this it will take time to print it and it will take up much space in the file. It would be a lot simpler to have a jinja for loop that renders the file before it is read by the YAML module.

Another example could be to simplify fields that is used over and over again that uses a online to render a complete field. Many times i have the same config for a string field for example.

If this feature would be acceptible i could put in the time to make it happen.

**Comment by thde** [comment]
I like the idea. It gives much more flexibility. And it shouldn't be a big change as well right?

**Comment by Grokzen** [comment]
I will see what i can wip up and submit a PR during the weekend

**Comment by cimnine** [comment]
> Many times i have the same config for a string field for example.

You can also leverage YAML references to partially achieve what you want:

```yaml
# custom_fields.yaml
dns_server_1: &dns_servers
  type: selection
  label: Primary DNS
  required: true
  filterable: true
  weight: 90
  on_objects:
  - ipam.models.Prefix
  coices:
  - value: 1.1.1.1
  - value: 1.0.0.1
  - value: 8.8.8.8
  - value: 8.8.4.4
  - value: 9.9.9.9
  - value: 149.112.112.112
dns_server_2:
  <<: *dns_servers
  label: Secondary DNS
  weight: 91
```

Both selection fields will have the same choices. This is standard YAML.

If you still feel like Jinja is a good fit for this, please feel free to open a PR.

With this, I'm going to close this issue as there has been no discussion for more than two weeks.
